language: php

php:
  - 7.0

matrix:
  include:
    - php: 7.0
      env:
        - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - PHPSPEC_FLAGS="-c phpspec.yml.ci"
        - COVERAGE=true

install:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script: vendor/bin/phpspec run ${PHPSPEC_FLAGS}

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
